trigger:
- main

pr:
- main

jobs:
- job: RunContainerTests
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '3.x'

  - task: DockerInstaller@0
    inputs:
      dockerVersion: '17.09.0-ce'
      releaseType: 'stable'

  - script: docker pull dynatrace/dynatrace-configuration-as-code:latest
    displayName: 'Pull Docker Image'

  - script: |
      docker run -it --entrypoint /bin/sh dynatrace/dynatrace-configuration-as-code
      monaco version
      sleep 10
    displayName: 'Run Docker Container'

  - script: docker stop my_container
    displayName: 'Stop Docker Container'

  - script: docker rm my_container
    displayName: 'Remove Docker Container'
