# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    #export DT_OAUTH_CLIENT_SECRET_ENV_VAR=$(DT_OAUTH_CLIENT_SECRET_ENV_VAR)
    #export DT_TOKEN_ENV=$(DT_TOKEN_ENV)
    #sed -i "s/{{service}}/${SERVICE_NAME}/g" config-as-code/configs.yaml
    #chmod +x ./monaco

    #./monaco deploy manifest.yaml
    docker pull dynatrace/dynatrace-configuration-as-code:latest
    docker run \
    --env API_TOKEN=$(DT_TOKEN_ENV)\
    --mount type=bind,src="project-monaco",target=/monaco \
    dynatrace/dynatrace-configuration-as-code:latest deploy -d manifest.yaml
  displayName: 'Run Monaco'
