trigger:
- main

jobs:
- job: RunMonaco
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - checkout: self

  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(Build.SourcesDirectory)'  # Path to the root of your repository
      Contents: 'monaco-demo/'  # Name of the file you want to copy
      TargetFolder: '$(Agent.BuildDirectory)/doc/'  # Target folder in the Docker container
      OverWrite: true
    displayName: 'Copy docs to Docker container'

  - script: docker pull dynatrace/dynatrace-configuration-as-code:latest
    displayName: 'Pull Docker Image'
    
  - script: |
      docker run --mount type=bind,src="$(Agent.BuildDirectory)/doc/",target=/monaco dynatrace/dynatrace-configuration-as-code deploy -d manifest.yaml
    displayName: 'Run Docker Container'