trigger:
- main

jobs:
- job: RunMonaco
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - checkout: self

  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(Build.SourcesDirectory)/monaco-demo'  # Path to the monaco-demo folder in your repository
      Contents: '**/*'  # Match all files and subdirectories
      TargetFolder: '$(Agent.BuildDirectory)/doc'  # Target folder in the Docker container
      OverWrite: true
    displayName: 'Copy Docs to Docker container'

  - script: docker pull dynatrace/dynatrace-configuration-as-code:latest
    displayName: 'Pull Monaco Image'
    
  - script:  docker run --mount type=bind,src="$(Agent.BuildDirectory)/doc/",target=/monaco dynatrace/dynatrace-configuration-as-code deploy -d manifest.yaml
    env:
      TOKEN: $(DT_TOKEN)
      OAUTH_CLIENT_ID: $(DT_OAUTH_CLIENT_ID)
      OAUTH_CLIENT_SECRET: $(DT_OAUTH_CLIENT_SECRET)
    displayName: 'Run Monaco Container'