trigger:
- main

pr:
- main

jobs:
- job: RunContainerTests
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '3.x'

  - task: DockerInstaller@0
    inputs:
      dockerVersion: '17.09.0-ce'
      releaseType: 'stable'

  - script: docker pull <your_container_image>:latest
    displayName: 'Pull Docker Image'

  - script: |
      docker run -d --name my_container <your_container_image>:latest
      sleep 10
    displayName: 'Run Docker Container'

  - script: |
      docker ps | grep my_container | grep -q " Up " || exit 1
      docker exec my_container moanco deploy manifest.yaml || exit 1
    displayName: 'Execute moanco deploy inside Container'

  - script: docker stop my_container
    displayName: 'Stop Docker Container'

  - script: docker rm my_container
    displayName: 'Remove Docker Container'
