trigger:
- main

jobs:
- job: RunMonaco
  pool:
    vmImage: 'ubuntu-latest'

  steps:
    - task: CopyFiles@2
    inputs:
      SourceFolder: '$(Build.SourcesDirectory)' 
      Contents: 'manifest.yaml'  
      TargetFolder: '/doc'  
      OverWrite: true
    displayName: 'Copy manifest.yaml to Docker container'

  - script: docker pull dynatrace/dynatrace-configuration-as-code:latest
    displayName: 'Pull Docker Image'
    
  - script: |
      docker run --mount type=bind,src="/",target=/monaco dynatrace/dynatrace-configuration-as-code deploy -d /doc/manifest.yaml
    displayName: 'Run Docker Container'
