trigger:
- main

jobs:
- job: RunMonaco
  pool:
    vmImage: 'ubuntu-latest'

  steps:

  - script: docker pull dynatrace/dynatrace-configuration-as-code:latest
    displayName: 'Pull Docker Image'
    
  - script: |
      docker run dynatrace/dynatrace-configuration-as-code deploy -d manifest.yaml
      sleep 10
    displayName: 'Run Docker Container'
