# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- bash: |
    docker pull dynatrace/dynatrace-configuration-as-code:latest
    ll
    docker run --name monaco \
    dynatrace/dynatrace-configuration-as-code:latest deploy -d monaco-demo/manifest.yaml
  env:
    TOKEN: $(DT_TOKEN_ENV)
    OAUTH_CLIENT_ID: $(DT_OAUTH_CLIENT_ID)
    OAUTH_CLIENT_SECRET: $(DT_OAUTH_CLIENT_SECRET)
  displayName: 'Deploy mani'