trigger:
- main

pr:
- main

jobs:
- job: RunContainerTests
  pool:
    vmImage: 'ubuntu-latest'

  steps:

  - task: DockerInstaller@0
    inputs:
      dockerVersion: '17.09.0-ce'
      releaseType: 'stable'

  - script: docker pull dynatrace/dynatrace-configuration-as-code:latest
    displayName: 'Pull Docker Image'
    
  - script: |
      docker run dynatrace/dynatrace-configuration-as-code version
      sleep 10
    displayName: 'Run Docker Container'

