
trigger:
- main

jobs:
- job: RunMonaco
  pool:
    vmImage: 'ubuntu-latest'

  steps:

  - task: Docker@2
    displayName: 'Pull Docker Image'
    inputs:
      command: 'pull'
      repository: 'dynatrace/dynatrace-configuration-as-code'
      tags: 'latest'

  - task: Docker@2
    displayName: 'Run Docker Container'
    inputs:
      command: 'run'
      repository: 'dynatrace/dynatrace-configuration-as-code'
      tags: 'latest'
      #options: '-e API_TOKEN=XXX'  # Set environment variable
      containerCommand: 'deploy -d manifest.yaml'  # Specify the command to run inside the container
      failOnStderr: true  # Fail the task if the command inside the container returns an error